version: '3.1'

services:

  wordpress:
    image: wordpress
    container_name: wordpresscompose
    restart: always
    ports:
      - 8089:80
    environment:
      WORDPRESS_DB_HOST: db_wp
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: 123456
      WORDPRESS_DB_NAME: wp12
    volumes:
      - wordpress:/var/www/html

  db_wp:
    image: mysql
    container_name: mysqlcomposeforwordpress
    restart: always
    environment:
      MYSQL_DATABASE: wp12
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123456
      MYSQL_RANDOM_ROOT_PASSWORD: 123
    volumes:
      - db_wp:/var/lib/mysql

volumes:
  wordpress:
  db_wp:
